### PR TITLE
variant_lantern compat

### PR DESCRIPTION
**Pull request by xanthian**
Includes Gold (Normal, Soul & Redstone) and Iron (Redstone variant) base lanterns.
Includes all variants from 'Tech Reborn' pack

Havent tested with every lantern yet.

also build seems to be failing atm due to a 403 error on the modcompile of secret-rooms-fabric when trying to build, not related to this PR.
I made another branch and removed the mixin, and secret-rooms stuff to test the build, all seems to be good.
please dont accept this PR yet, as it is WIP and my mod is not released.

### CODE REVIEW

**Comment by xanthian** [comment]
tested with all lanterns in my mod, no issues

**Comment by ThePoultryMan** [comment]
Sorry about this, but I have changed the placement system used. I forgot about the update I've had on the back burner. With these changes, the `on_wall` blockstate has been removed. This change also means that `hanging` now has to be false. _Luckily_, you should be able to do what I did and just find and replace within each file.

After these changes, I'm happy to merge.

**Comment by xanthian** [comment]
so    
     "hanging=true,on_wall=true,facing=north": {
to
        "hanging=false,facing=north": {
 ?

**Comment by ThePoultryMan** [comment]
That is correct.

**Comment by xanthian** [comment]
added.

**Comment by ThePoultryMan** [comment]
I'm going to release this update tomorrow.

**Pull request merged**
